"""Unified eSIM Gateway models."""

# Catalog models
# Account/wallet models
from esim_gateway.models.account import (
    AccountBalance,
    AccountInfo,
    GetAccountInfoResponse,
    GetBalanceResponse,
    ListTransactionsRequest,
    ListTransactionsResponse,
    RefundRequest,
    RefundResponse,
    TopUpRequest,
    TopUpResponse,
    Transaction,
    TransactionStatus,
    TransactionType,
)
from esim_gateway.models.catalog import (
    Country,
    DataAllowance,
    ErrorDetail,
    ErrorResponse,
    GetPackageResponse,
    ListCountriesResponse,
    ListPackagesRequest,
    ListPackagesResponse,
    ListRegionsResponse,
    Network,
    Package,
    Region,
    SmsAllowance,
    VoiceAllowance,
)

# eSIM management models
from esim_gateway.models.esim import (
    ApplyBundleRequest,
    ApplyBundleResponse,
    AssignedBundle,
    BundleStatus,
    ESim,
    ESimHistory,
    ESimStatus,
    GetBundleStatusResponse,
    GetESimHistoryResponse,
    GetESimResponse,
    ListESimBundlesResponse,
    ListESimsRequest,
    ListESimsResponse,
    RevokeBundleRequest,
    RevokeBundleResponse,
)

# Inventory models
from esim_gateway.models.inventory import (
    AssignmentInfo,
    BundleGroup,
    BundleGroupType,
    GetBundleGroupResponse,
    GetInventoryItemResponse,
    InventoryItem,
    InventorySummary,
    InventoryType,
    ListAssignmentsRequest,
    ListAssignmentsResponse,
    ListBundleGroupsResponse,
    ListInventoryRequest,
    ListInventoryResponse,
    RestockRequest,
    RestockResponse,
)

# Order models
from esim_gateway.models.order import (
    CreateOrderRequest,
    CreateOrderResponse,
    CustomerInfo,
    ESimActivation,
    GetOrderResponse,
    ListOrdersRequest,
    ListOrdersResponse,
    Order,
    OrderItem,
)

# Usage models
from esim_gateway.models.usage import (
    DataUsage,
    GetUsageHistoryRequest,
    GetUsageHistoryResponse,
    GetUsageRequest,
    GetUsageResponse,
    SmsUsage,
    UsageHistory,
    UsageRecord,
    UsageStats,
    UsageType,
    UsageUnit,
    VoiceUsage,
)

__all__ = [
    # Catalog
    "Country",
    "DataAllowance",
    "ErrorDetail",
    "ErrorResponse",
    "GetPackageResponse",
    "ListCountriesResponse",
    "ListPackagesRequest",
    "ListPackagesResponse",
    "ListRegionsResponse",
    "Network",
    "Package",
    "Region",
    "SmsAllowance",
    "VoiceAllowance",
    # Order
    "CreateOrderRequest",
    "CreateOrderResponse",
    "CustomerInfo",
    "ESimActivation",
    "GetOrderResponse",
    "ListOrdersRequest",
    "ListOrdersResponse",
    "Order",
    "OrderItem",
    # eSIM
    "ApplyBundleRequest",
    "ApplyBundleResponse",
    "AssignedBundle",
    "BundleStatus",
    "ESim",
    "ESimHistory",
    "ESimStatus",
    "GetBundleStatusResponse",
    "GetESimHistoryResponse",
    "GetESimResponse",
    "ListESimBundlesResponse",
    "ListESimsRequest",
    "ListESimsResponse",
    "RevokeBundleRequest",
    "RevokeBundleResponse",
    # Usage
    "DataUsage",
    "GetUsageHistoryRequest",
    "GetUsageHistoryResponse",
    "GetUsageRequest",
    "GetUsageResponse",
    "SmsUsage",
    "UsageHistory",
    "UsageRecord",
    "UsageStats",
    "UsageType",
    "UsageUnit",
    "VoiceUsage",
    # Account
    "AccountBalance",
    "AccountInfo",
    "GetAccountInfoResponse",
    "GetBalanceResponse",
    "ListTransactionsRequest",
    "ListTransactionsResponse",
    "RefundRequest",
    "RefundResponse",
    "TopUpRequest",
    "TopUpResponse",
    "Transaction",
    "TransactionStatus",
    "TransactionType",
    # Inventory
    "AssignmentInfo",
    "BundleGroup",
    "BundleGroupType",
    "GetBundleGroupResponse",
    "GetInventoryItemResponse",
    "InventoryItem",
    "InventorySummary",
    "InventoryType",
    "ListAssignmentsRequest",
    "ListAssignmentsResponse",
    "ListBundleGroupsResponse",
    "ListInventoryRequest",
    "ListInventoryResponse",
    "RestockRequest",
    "RestockResponse",
]
